//
//  CustomerRouter.swift
//  IOSProject
//
//  Created by Jason Barrios on 3/20/19.
//  Copyright (c) 2019 Jason Barrios. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CustomerRoutingLogic
{
  func goToNextView(indexPath: IndexPath)
}

protocol CustomerDataPassing
{
  var dataStore: CustomerDataStore? { get set }
}

class CustomerRouter: NSObject, CustomerRoutingLogic, CustomerDataPassing
{
  weak var viewController: CustomerViewController?
  var dataStore: CustomerDataStore?
  
  // MARK: Routing
  
    // MARK: Routing
    func goToNextView(indexPath: IndexPath) {
        if let customer = dataStore?.getItemSelected(indexPath: indexPath)
        {
            if let detailViewController = R.storyboard.login().instantiateInitialViewController() as? CustomDetailViewController {
                
                detailViewController.router?.dataStore?.customer = customer
                viewController?.navigationController?.pushViewController(detailViewController, animated: true)
                
            }
        }
    }
}
