//
//  CustomerModels.swift
//  IOSProject
//
//  Created by Jason Barrios on 3/20/19.
//  Copyright (c) 2019 Jason Barrios. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Customer
{
    // MARK: Use cases
    
    enum DataSource
    {
        struct Request {
            var username: String
        }
        struct Response {
            var items: [CustomerModel]?
            var error: ServiceError?
        }
        struct ViewModel {
            struct DisplayedItem {
                var businessname: String?
                var name: String?
                var dni: String?
                var id: Int?
            }
            var displayedItems: [DisplayedItem]
        }
    }
}
