//
//  CustomDetailModels.swift
//  IOSProject
//
//  Created by Jason Barrios on 3/23/19.
//  Copyright (c) 2019 Jason Barrios. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CustomDetail
{
  // MARK: Use cases
  
    enum UIInformation {
        struct Request {
        }
        struct Response {
            var item: CustomerModel?
        }
        struct ViewModel {
            struct DisplayedItem {
                var businessname: String?
                var name: String?
                var dni: String?
                var id: Int?
            }
            var displayedItem: DisplayedItem
        }
    }
}
