//
//  CustomDetailPresenter.swift
//  IOSProject
//
//  Created by Jason Barrios on 3/23/19.
//  Copyright (c) 2019 Jason Barrios. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CustomDetailPresentationLogic
{
  func presentUIInformation(response: CustomDetail.UIInformation.Response)
}

class CustomDetailPresenter: CustomDetailPresentationLogic
{
  weak var viewController: CustomDetailDisplayLogic?
  
  // MARK: Do something
  
    func presentUIInformation(response: CustomDetail.UIInformation.Response) {
        
        let customer = CustomDetail.UIInformation.ViewModel.DisplayedItem.init(businessname: response.item?.BusinessName, name: response.item?.Name, dni: response.item?.Dni, id: response.item?.Id)
        
        
        viewController?.displayUIInformation(viewModel: CustomDetail.UIInformation.ViewModel.init(displayedItem: customer))
    }
}
