//
//  CustomDetailViewController.swift
//  IOSProject
//
//  Created by Jason Barrios on 3/23/19.
//  Copyright (c) 2019 Jason Barrios. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CustomDetailDisplayLogic: class
{
    func displayUIInformation(viewModel: CustomDetail.UIInformation.ViewModel)
}

class CustomDetailViewController: UIViewController, CustomDetailDisplayLogic
{
  var interactor: CustomDetailBusinessLogic?
  var router: (NSObjectProtocol & CustomDetailRoutingLogic & CustomDetailDataPassing)?

  // MARK: Object lifecycle
    @IBOutlet weak var txtCustomerInfo: UITextView!
    
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = CustomDetailInteractor()
    let presenter = CustomDetailPresenter()
    let router = CustomDetailRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
    override func viewDidLoad()
    {
        super.viewDidLoad()
        requestUIIformation()
    }
    
    // MARK: Request logic
    func requestUIIformation() {
        interactor?.requestUIInformation(request: CustomDetail.UIInformation.Request())
    }
    
    
    // MARK: Display logic
    func displayUIInformation(viewModel: CustomDetail.UIInformation.ViewModel) {
        let display = viewModel.displayedItem
        title = display.name
        txtCustomerInfo.text = "Identificador: \(display.dni ?? "")\n Nombre negocio: \(display.businessname ?? "")"
    }
}
