//
//  InvoicePresenter.swift
//  IOSProject
//
//  Created by Jason Barrios on 3/19/19.
//  Copyright (c) 2019 Jason Barrios. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InvoicePresentationLogic {
    func presentDataSource(response: Invoice.DataSource.Response)
}

class InvoicePresenter: InvoicePresentationLogic {
    weak var viewController: InvoiceDisplayLogic?
    
    // MARK: presenter logic
    func presentDataSource(response: Invoice.DataSource.Response) {
        if let error = response.error {
            print("HAY UN ERROR: \(error)")
            return
        }
        if let invoices = response.items {
            let displayedInvoices = invoices.map({Invoice.DataSource.ViewModel.DisplayedItem.init(invoicenumber: $0.InvoiceNumber, invoicecodemh: $0.InvoiceCodeMH, grossprice: $0.GrossPrice, netprice: $0.NetPrice, createdate: $0.CreateDate, id: $0.Id)})
            viewController?.displayDataSource(viewModel: Invoice.DataSource.ViewModel.init(displayedItems: displayedInvoices))
        }
    }
}
