//
//  InvoiceModels.swift
//  IOSProject
//
//  Created by Jason Barrios on 3/19/19.
//  Copyright (c) 2019 Jason Barrios. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Invoice
{
  // MARK: Use cases
  
  enum DataSource
  {
    struct Request {
        var username: String
    }
    struct Response {
        var items: [InvoiceModel]?
        var error: ServiceError?
    }
    struct ViewModel {
        struct DisplayedItem {
            var invoicenumber: String?
            var invoicecodemh: String?
            var grossprice: Decimal?
            var netprice: Decimal?
            var createdate: String
            var id: Int?
        }
        var displayedItems: [DisplayedItem]
    }
  }
}

