//
//  LoginModels.swift
//  IOSProject
//
//  Created by Jason Barrios on 3/21/19.
//  Copyright (c) 2019 Jason Barrios. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum User
{
    // MARK: Use cases
    
    enum DataSource
    {
        struct Request {
            var username: String
            var password: String
        }
        struct Response {
            var items: [UserModel]?
            var error: ServiceError?
        }
        struct ViewModel {
            struct UserValid {
                var isOk: Bool?
                var name: String?
                var dni: String?
                var id: Int?
            }
            var user : UserValid
        }
    }
}
