//
//  LoginViewController.swift
//  IOSProject
//
//  Created by Jason Barrios on 3/21/19.
//  Copyright (c) 2019 Jason Barrios. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginDisplayLogic: class
{
    func checkUser(viewModel: User.DataSource.ViewModel)
}

class LoginViewController: UIViewController, LoginDisplayLogic {
    
    var interactor: LoginBusinessLogic?
    var router: (NSObjectProtocol & LoginRoutingLogic & LoginDataPassing)?
    //private let customCellIdentifier = "CustomInvoiceTableViewCell"
    
    // MARK: IBOutlets
    @IBOutlet weak var txtUsername: UITextField!
    @IBOutlet weak var txtPassword: UITextField!
    
    @IBAction func btnLoginAction(_ sender: Any) {
        let username = txtUsername.text ?? ""
        let password = txtPassword.text ?? ""
        requestDataSource(username: username, password: password)
    }
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = LoginInteractor()
        let presenter = LoginPresenter()
        let router = LoginRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        txtPassword.isSecureTextEntry = true
    }
    
    // MARK: Request logic
    func requestDataSource(username: String, password: String) {
        //activityIndicator.show(in: view)
        let request = User.DataSource.Request.init(username: username, password: password)
        interactor?.requestDataSource(request: request)
    }
    
    
    // MARK: Display logic
    func checkUser(viewModel: User.DataSource.ViewModel) {
        let user = viewModel.user
        if user.isOk == true {
//            let customTabViewController =  storyboard!.instantiateViewController(withIdentifier: "CustomTabBarViewController")
//            changeRootViewController(viewController: customTabViewController)
            let username = txtUsername.text ?? ""
            router?.goToNextView(username: username, name: user.name ?? "")
        }
    }
    
//    func changeRootViewController(viewController: UIViewController) {
//        let appDelegate  = UIApplication.shared.delegate as! AppDelegate
//        let snapshot:UIView = (appDelegate.window!.snapshotView(afterScreenUpdates: true))!
//        viewController.view.addSubview(snapshot)
//        appDelegate.window!.rootViewController = viewController
//        UIView.animate(withDuration: 0.3, animations: {() in
//            snapshot.layer.opacity = 0;
//            snapshot.layer.transform = CATransform3DMakeScale(1.5, 1.5, 1.5)
//        }, completion: {
//            (value: Bool) in
//            snapshot.removeFromSuperview();
//        });
//    }
}
