//
//  LoginPresenter.swift
//  IOSProject
//
//  Created by Jason Barrios on 3/21/19.
//  Copyright (c) 2019 Jason Barrios. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func checkUser(response: User.DataSource.Response)
}

class LoginPresenter: LoginPresentationLogic {
    weak var viewController: LoginDisplayLogic?
    
    // MARK: presenter logic
    func checkUser(response: User.DataSource.Response) {
        if let error = response.error {
            print("HAY UN ERROR: \(error)")
            return
        }
        if let users = response.items {
            let user = users.first
            let uservalid = User.DataSource.ViewModel.UserValid.init(isOk: true, name: user?.Name, dni: user?.Dni, id: user?.Id)
            viewController?.checkUser(viewModel: User.DataSource.ViewModel.init(user: uservalid))

        }
    }
}
