//
//  InvoiceDetailInteractor.swift
//  IOSProject
//
//  Created by Jason Barrios on 3/23/19.
//  Copyright (c) 2019 Jason Barrios. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InvoiceDetailBusinessLogic
{
  func requestUIInformation(request: InvoiceDetail.UIInformation.Request)
}

protocol InvoiceDetailDataStore
{
  var invoice: InvoiceModel? { get set }
}

class InvoiceDetailInteractor: InvoiceDetailBusinessLogic, InvoiceDetailDataStore
{
    
  var presenter: InvoiceDetailPresentationLogic?
  var worker: InvoiceDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
    var invoice: InvoiceModel?
    
    func requestUIInformation(request: InvoiceDetail.UIInformation.Request) {
        if let invoice = invoice {
            presenter?.presentUIInformation(response: InvoiceDetail.UIInformation.Response.init(item: invoice))
        }
    }
}
